//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abteilung
    {
        public abteilung()
        {
            this.mitarbeiter = new HashSet<mitarbeiter>();
        }
    
        public int abteilung_id { get; set; }
        public string bezeichnung { get; set; }
        public string aufgaben { get; set; }
    
        public virtual ICollection<mitarbeiter> mitarbeiter { get; set; }
    }
}
