//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auftraggeber
    {
        public auftraggeber()
        {
            this.projekt = new HashSet<projekt>();
        }
    
        public int auftraggeber_id { get; set; }
        public string bezeichnung { get; set; }
        public string kurzname { get; set; }
        public string adr_strasse { get; set; }
        public string adr_plz { get; set; }
        public string adr_ort { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string sonderkonditionen { get; set; }
    
        public virtual ICollection<projekt> projekt { get; set; }
    }
}
