//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mitarbeiter
    {
        public mitarbeiter()
        {
            this.projekt = new HashSet<projekt>();
        }
    
        public int person_id { get; set; }
        public string name { get; set; }
        public string vorname { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public Nullable<decimal> gehalt { get; set; }
        public string stellung { get; set; }
        public int fk_abteilung_id { get; set; }
    
        public virtual abteilung abteilung { get; set; }
        public virtual ICollection<projekt> projekt { get; set; }
    }
}
