//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projekt
    {
        public int projekt_id { get; set; }
        public string bezeichnung { get; set; }
        public string beschreibung { get; set; }
        public Nullable<System.DateTime> beginn { get; set; }
        public Nullable<System.DateTime> ende { get; set; }
        public Nullable<decimal> auftragsvolumen { get; set; }
        public Nullable<int> fk_auftraggeber_id { get; set; }
        public Nullable<int> fk_projektleiter_id { get; set; }
    
        public virtual auftraggeber auftraggeber { get; set; }
        public virtual mitarbeiter mitarbeiter { get; set; }
    }
}
